site_name: Beyond the Horizon
site_description: 'Documentação para o RPG Beyond the Horizon (BTH)'
site_author: 'Henrique Schorr'
docs_dir: docs/
# repo_name: 'mhausenblas/mkdocs-template'
# repo_url: 'https://github.com/mhausenblas/mkdocs-template'

nav:
    - Home: index.md
    - Regras: regras/introduction.md
      - regras/character.md

extra_css:
  - stylesheets\extra.css
extra_javascript:
  - javascripts\list.js

theme:
  name: 'material'
  custom_dir: theme

markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: False
    - toc:
        permalink: True
    - footnotes
    - pymdownx.details