site_name: Beyond the Horizon
theme:
  name: "material"
  font:
    title: Orbitron
    text: Roboto
  palette:
    primary: black
    accent: deep purple
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
# site_description: 'Documentação para o RPG Horizon Beyond (HB)'
# site_author: 'Henrique Schorr'
# docs_dir: docs
# repo_name: 'mhausenblas/mkdocs-template'
# repo_url: 'https://github.com/mhausenblas/mkdocs-template'

nav:
    - index.md
    # - Links Úteis: links.md
    - Manuscrito (Jogador):
      - 0_complete/1_manuscript_player/index.md
      - Seu Personagem:
        - 0_complete/1_manuscript_player/character/index.md
        # properties
        - Atributos: 0_complete/1_manuscript_player/character/attributes.md
        # - Conhecimento: ciencia e receitas
        # Senses
        - Resiliência: 0_complete/1_manuscript_player/character/resilience.md #resiliencia, nível de stress, panic roll, parando panico, recuperação
        - Moves: 0_complete/1_manuscript_player/character/moves.md #ações, reações, habilidades, movimento, ambushes e sneak attack, usando equipamento, comunicação
        - Habilidades: 0_complete/1_manuscript_player/character/abilities.md #passiva, engatilhadas, ativas        
        - Armas: 0_complete/1_manuscript_player/character/weapons.md #features, propriedades
        - Armadura: 0_complete/1_manuscript_player/character/armor.md
        #   Equipamentos: features, propriedades
        #   Consumíveis: composto químicos e etc
        # recursos e suprimentos
        # - Inventário: 0_complete/1_manuscript_player/character/inventory.md
        #   Transport: veículos e montarias
        #   Companions: orgânicos e sintéticos 
        # - Progressão: 0_complete/1_manuscript_player/character/progression.md
    #   Equipe:
    #     Geral: nome, membros, etc
    #     Agenda: objetivos, missão, etc
    #     Suprimentos: agua, comida, ar, energia, checks de suprimentos
    #     Recursos: momentum e karma
      # - Checks: 0_complete/1_manuscript_player/checks.md         
    #   Scene Modes: exploration, combat, conflito social (negociação e interrogação), investigação, perseguição ou fuga, stealth, rest
      # - Combate: 0_complete/1_manuscript_player/combat/index.md
      # - Dano e Pânico: 0_complete/1_manuscript_player/combat/damage.md      
    #   Condições: buffs e aflições
    #   Hazards: armadilhas, vacuo, explosões, radiação, starving, desidratação, exaustão, freezing, queda, fogo, doença, afogamento, sufocamento
    #   Descanso: bla bla recuperação e crafting    
    #   Crafting: e tal
    #   Criaturas: propriedades, nível de ameaça
    

    # Força Galática:
    #   overview: o que é, espécies, temas
    #   História: timeline
    #   Estrutura: social, economica, religião, planetas, estações, organizações
    #   Agenda: objetivos, interesses e etc
    #   Criando Humanos:
    #     Caminhos: ordinários x super
    #     Ordinários:
    #       overview: características, agenda, oportunidades
    #       Caminhos: blabla
    #       moves: moves
    #       abilities: abilities
    #       weapons: weapons
    #       armor: armor
    #       equipment: equipment
    #       recipes: recipes
    #       aprimoramentos: lista
    #     super:
    #       overview: características, agenda, oportunidades
    #       Caminhos: blabla
    #       moves: moves
    #       abilities: abilities
    #       weapons: weapons
    #       armor: armor
    #       equipment: equipment
    #       recipes: recipes  
    #       aprimoramentos: lista
    #   Sistema: planetas de interesse e etc
    #   Ameaças: criaturas, organizações, etc
    #   Aventuras: lista de possíveis gatilhos e tal
    #   Aventura exemplo: aqui


      # - Personagem:
      #   - 1_simplified/1_core/2_character/index.md
      # - O Jogo:
      #   - 1_simplified/1_core/3_game/index.md
      #   - Atributos: 1_simplified/1_core/3_game/attributes.md
      #   - Combate: 1_simplified/1_core/3_game/combat.md
      #   - Moves: 1_simplified/1_core/3_game/moves.md
      #   - Habilidades: 1_simplified/1_core/3_game/abilities.md
        # - Passivas: 1_simplified/1_core/3_game/passives.md
    #     - Checks: 1_simplified/1_core/3_game/checks.md
    #     - Resiliência: 1_simplified/1_core/3_game/resilience.md
    #     - Recursos: 1_simplified/1_core/3_game/resources.md
    #     - Conhecimento: 1_simplified/1_core/3_game/knowledge.md
    #     - Dano: 1_simplified/1_core/3_game/damage.md
    #     - Condições: 1_simplified/1_core/3_game/conditions.md
    #     - Countdowns: 1_simplified/1_core/3_game/countdown.md
    #     - Distância e Tamanho: 1_simplified/1_core/3_game/distance.md
    #     - Alvos e Proteção: 1_simplified/1_core/3_game/target.md
    #     - Descanso: 1_simplified/1_core/3_game/rest.md
    #     - Armas e Armaduras: 1_simplified/1_core/3_game/weapon_armor.md
    #     - Inventário, Equipamento e Munições: 1_simplified/1_core/3_game/inventory.md
    #     - Crafting: 1_simplified/1_core/3_game/crafting.md
    #     - Criaturas e Monstros: 1_simplified/1_core/3_game/creatures.md
    #     - Propriedades: 1_simplified/1_core/3_game/properties.md
    #     - Aprimoramentos: 1_simplified/1_core/3_game/upgrades.md
    # - Força Galáctica:
    #   - 1_simplified/2_galactic_force/index.md
    #   - Moves: 1_simplified/2_galactic_force/moves.md
    #   - Habilidades: 1_simplified/2_galactic_force/abilities.md
    #   - Armas: 1_simplified/2_galactic_force/weapons.md
    #   - Armaduras: 1_simplified/2_galactic_force/armor.md
    #   - Equipamentos: 1_simplified/2_galactic_force/equipment.md
    #   - Receitas: 1_simplified/2_galactic_force/recipes.md

    # - Manuscrito:
    #   - 1_core/index.md
    #   # - Comece Aqui: 1_core/1_start/index.md
    #   - Personagem:
    #     - 1_core/2_character/index.md
    #     - Exemplo: 1_core/2_character/example.md
    #     - Espécies: 1_core/2_character/species.md
    #     - Cartas: 1_core/2_character/cards.md
    #   - O Jogo:
    #     - 1_core/3_game/index.md
    #     - Combate: 1_core/3_game/combat.md
    #     - Conflito Social: 1_core/3_game/social.md
    #     - Ações e Reações:  1_core/3_game/actions.md
    #     - Checks: 1_core/3_game/checks.md
    #     - Recursos: 1_core/3_game/resources.md
    #     - Dano e Resiliência: 1_core/3_game/damage.md
    #     - Condições: 1_core/3_game/conditions.md
    #     - Countdowns: 1_core/3_game/countdown.md
    #     - Distância, Movimento e Tamanho: 1_core/3_game/distance.md
    #     - Alvos, Proteção e Visão: 1_core/3_game/target.md        
    #     - Descanso, Morte e Trauma: 1_core/3_game/death.md              
    #     - Armas e Armaduras: 1_core/3_game/weapon_armor.md
    #     - Propriedades: 1_core/3_game/properties.md
    #     - Inventário, Equipamentos e Munições: 1_core/3_game/inventory.md    
    #     - Crafting: 1_core/3_game/crafting.md  
    #     - Companion: 1_core/3_game/companion.md   
    #     - Transporte: 1_core/3_game/transport.md
    #     - Criaturas e Monstros: 1_core/3_game/creatures.md
    # - Força Galáctica:
    #   - 2_galactic_force/index.md
    #   - Criando um Humano: 2_galactic_force/creation.md
    #   - Armas: 2_galactic_force/weapons.md
    #   - Armaduras: 2_galactic_force/armor.md
    #   - Equipamentos: 2_galactic_force/equipment.md
    #   - Crafting: 2_galactic_force/crafting.md
    #   - Companion: 2_galactic_force/companion.md
    #   - Transporte: 2_galactic_force/transport.md   
    #   - Cartas: 2_galactic_force/cards.md   
    #   # - Humanos:
    #   # - Mapa:
    #   # - Perigos:
    #   # - Aventuras:
    # - Cursed Set:
    #     - 666_cursed_set/index.md  
    #     - Atos: 666_cursed_set/acts.md
    #     - Profissões: 666_cursed_set/professions.md
    # - Baile Carnificina:
    #     - 696_carnage_ball/index.md
    #     - CarnArk:
    #         - 696_carnage_ball/carnark/index.md
    #         - Loja: 696_carnage_ball/carnark/shop.md
    #         - Perigos: 696_carnage_ball/carnark/hazards.md
    #         - Condições: 696_carnage_ball/carnark/conditions.md
    #     - Bailes:
    #         - 696_carnage_ball/balls/index.md
    #         - Patrocínio: 696_carnage_ball/balls/sponsor.md
    #     - Pré-Jogo: 696_carnage_ball/pre_game.md

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - toc:
      permalink: 
  - attr_list
  - md_in_html
      
