site_name: Beyond the Horizon
site_description: 'Documentação para o RPG Beyond the Horizon (BTH)'
site_author: 'Henrique Schorr'
docs_dir: docs
# repo_name: 'mhausenblas/mkdocs-template'
# repo_url: 'https://github.com/mhausenblas/mkdocs-template'

nav:
  - Home: index.md
  # - Regras: 
  - Introdução: introduction.md
  - Personagem: character.md

extra_css:
  - stylesheets\extra.css
extra_javascript:
  - javascripts\list.js

theme:
  name: 'material'
  custom_dir: theme
  logo: images/logo.png
  site_favicon: images/logo.png
  palette:
    primary: blue
    accent: light blue
  feature:
    tabs: false

markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: False
    - toc:
        permalink: True
    - footnotes
    - pymdownx.details