site_name: Beyond the Horizon
theme:
  name: 'material'
  font:
    title: Orbitron
    text: Roboto
# site_description: 'Documentação para o RPG Beyond the Horizon (BTH)'
# site_author: 'Henrique Schorr'
# docs_dir: docs
# repo_name: 'mhausenblas/mkdocs-template'
# repo_url: 'https://github.com/mhausenblas/mkdocs-template'

nav:
  - Home: index.md
  - Regras: 
    - Introdução: rules/introduction.md
    - Personagem: 
      - Espécies: rules/character/species.md
      - Atributos:
        - Aptidões: rules/character/aptitudes.md
        - Competências: rules/character/skills.md
      - Resiliência: rules/character/resilience.md
      - Anatomia: rules/character/anatomy.md
      - Velocidades: rules/character/speeds.md
      - Conhecimento Científico: rules/character/scienceKnowledge.md
      - Passivas: rules/character/passives.md
      - Ações, Reações e Habilidades: rules/character/actionsReactions.md
      - Armamentos e Armaduras: rules/character/weaponArmor.md
      - Inventário: rules/character/inventory.md
      - Descanso: rules/character/rests.md
      - Sobrevivência: rules/character/survival.md
      - Aprimoramentos: rules/character/upgrades.md
  - Humanos:
    - Introdução: species/human/introduction.md
  - Hivers:
    - Introdução: species/hiver/introduction.md
  - Symbions:
    - Introdução: species/symbion/introduction.md

extra_css:
  - stylesheets\extra.css
# extra_javascript:
#   - javascripts\list.js


  # custom_dir: theme
  # logo: images/logo.png
  # site_favicon: images/logo.png
  # palette:
  #   primary: blue
  #   accent: light blue
  # feature:
  #   - navigation.sections
  #   - navigation.instant
  #   - navigation.tabs
  #   - navigation.tabs.sticky
    # tabs: false

# markdown_extensions:
#     - admonition
#     - codehilite:
#         guess_lang: False
#     - toc:
#         permalink: True
#     - footnotes
#     - pymdownx.details